INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_USRPANALYZER usrpanalyzer)

FIND_PATH(
    USRPANALYZER_INCLUDE_DIRS
    NAMES usrpanalyzer/api.h
    HINTS $ENV{USRPANALYZER_DIR}/include
        ${PC_USRPANALYZER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    USRPANALYZER_LIBRARIES
    NAMES gnuradio-usrpanalyzer
    HINTS $ENV{USRPANALYZER_DIR}/lib
        ${PC_USRPANALYZER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(USRPANALYZER DEFAULT_MSG USRPANALYZER_LIBRARIES USRPANALYZER_INCLUDE_DIRS)
MARK_AS_ADVANCED(USRPANALYZER_LIBRARIES USRPANALYZER_INCLUDE_DIRS)

