#!/bin/bash

### BEGIN INIT INFO
# Provides:              msod
# Required-Start:        $all
# Required-Stop:         $all
# Default-Start:         2 3 4 5
# Default-Stop:          0 1 6
# Short-Description:     starts the msod server
# Description:           Measured Spectrum Occupancy Database and frontend Spectrum Browser
### END INIT INFO

NAME=msod
DESC="CAC Measured Spectrum Occupancy Database"

# To add another dependency, override this line in /etc/default/msod
SERVICES=(admin spectrumbrowser occupancy monitoring streaming)

if [[ -f /etc/default/${NAME} ]]; then
    source /etc/default/${NAME}
fi

source /lib/lsb/init-functions

start() {
    _check_superuser

    local s
    for s in ${SERVICES[@]}; do
        /sbin/service "$s" start
        sleep 1
    done
}

stop() {
    _check_superuser

    for (( i=${#SERVICES[@]}-1; i>=0; i-- )); do
        /sbin/service ${SERVICES[i]} stop
    done
}

status() {
    local s
    for s in ${SERVICES[@]}; do
        service "$s" status
    done
}

_print_usage_and_exit() {
    echo "Usage: service ${NAME} {start|stop|restart|status}" >>/dev/stderr
    exit 1
}

_check_superuser() {
    if (( ${EUID} != 0 )); then
        echo "${NAME} must be run with root priveleges" >>/dev/stderr
        _print_usage_and_exit
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        /sbin/service memcached restart
        start
        ;;
    status)
        status
        ;;
    *)
        _print_usage_and_exit
        ;;
esac

exit 0
