#!/bin/bash

### BEGIN INIT INFO
# Provides:              msod
# Required-Start:        memcached
# Required-Stop:         $all
# Default-Start:         2 3 4 5
# Default-Stop:          0 1 6
# Short-Description:     starts the msod server
# Description:           Measured Spectrum Occupancy Database and frontend Spectrum Browser
# chkconfig: - 65 35 016
### END INIT INFO

NAME=msod
DESC="CAC Measured Spectrum Occupancy Database"

# To add another dependency, override this line in /etc/default/msod
SERVICES=(servicecontrol admin spectrumbrowser occupancy monitoring streaming federation spectrumdb)

if [[ -f /etc/default/${NAME} ]]; then
    source /etc/default/${NAME}
fi

source /lib/lsb/init-functions

start() {
    _check_superuser
    rm -f /var/log/streaming.log
    rm -f /var/log/occupancy.log
    rm -f /var/log/servicecontrol.log
    rm -f /var/log/monitoring.log
    rm -f /var/log/admin.log
    rm -rf /var/log/flask
 
    if ! _memcached_running; then
        log_failure_msg "${NAME} requires memcached to be running"
        _print_usage_and_exit
    fi

    local s
    for s in ${SERVICES[@]}; do
        service "$s" start
        sleep 1
    done
}

_memcached_running() {
    service memcached status >/dev/null 2>&1
    return $?
}
stop() {
    _check_superuser

    for (( i=${#SERVICES[@]}-1; i>=0; i-- )); do
        service ${SERVICES[i]} stop
    done
}

status() {
    local s
    for s in ${SERVICES[@]}; do
        service "$s" status
    done
}

_print_usage_and_exit() {
    echo "Usage: service ${NAME} {start|stop|restart|status}" >>/dev/stderr
    exit 1
}

_check_superuser() {
    if (( ${EUID} != 0 )); then
        echo "${NAME} must be run with root priveleges" >>/dev/stderr
        _print_usage_and_exit
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        service memcached restart
        sleep 10
        start
        ;;
    status)
        status
        ;;
    *)
        _print_usage_and_exit
        ;;
esac

exit 0
