#!/bin/sh

CFG=/etc/msod/MSODConfig.json
PIDFILE=/tmp/occupancy.pid
LOGFILE=/var/log/occupancy.log
PYTHON=/usr/local/bin/python2.7
PYTHONPATH=/usr/local/lib/python2.7/site-packages/:/opt/SpectrumBrowser/flask

OPTIND=1
while getopts ":p:l:u:g:" opt; do
    case "$opt" in
        p)  PIDFILE=$OPTARG
            ;;
        l)  LOGFILE=$OPTARG
            ;;
        u)  RUN_AS=$OPTARG
            ;;
        g)  RUN_AS_GROUP=$OPTARG
            ;;
    esac
done
shift "$((OPTIND-1))"

if [ ! -f "$CFG" ]; then
    exit -1
fi

SB_HOME=$(
    ${PYTHON} -c 'import json; print json.load(open("'$CFG'"))["SPECTRUM_BROWSER_HOME"]'
)

cmd="nohup ${PYTHON} ${SB_HOME}/flask/OccupancyAlert.py --pidfile ${PIDFILE} >>${LOGFILE} 2>&1 &"
sudo -u ${RUN_AS} -g ${RUN_AS_GROUP} bash -c "$cmd"
