#!/bin/sh

CFG=/etc/msod/MSODConfig.json
PIDFILE=/var/run/streaming.pid
LOGFILE=/var/log/streaming.log
PYTHON=/usr/local/bin/python2.7

OPTIND=1
while getopts "p:l:" opt; do
    case "$opt" in
        p)  PIDFILE=$OPTARG
            ;;
        l)  LOGFILE=$OPTARG
            ;;
    esac
done
shift "$((OPTIND-1))"

if [ ! -f "$CFG" ]; then
    exit -1
fi

SB_HOME=$(
    ${PYTHON} -c 'import json; print json.load(open("'$CFG'"))["SPECTRUM_BROWSER_HOME"]'
)

nohup ${PYTHON} ${SB_HOME}/flask/StreamingServer.py --pidfile ${PIDFILE} >>${LOGFILE} 2>&1 &
