#!/bin/bash

CFG=/etc/msod/MSODConfig.json
PIDFILE=/tmp/dbmonitoring.pid
LOGFILE=/var/log/dbmonitoring.log
PYTHON=/usr/local/bin/python2.7
PYTHONPATH=/usr/local/lib/python2.7/site-packages/
DBPATH=/spectrumdb

OPTIND=1

while getopts "p:l:u:g:" opt; do
    case "$opt" in
        p)  PIDFILE=$OPTARG
            ;;
        l)  LOGFILE=$OPTARG
            ;;
        u)  RUN_AS=$OPTARG
            ;;
        g)  RUN_AS_GROUP=$OPTARG
            ;;
    esac
done

shift "$((OPTIND-1))"

if [ ! -f "$CFG" ]; then
    exit -1
fi

SB_HOME=$(
    ${PYTHON} -c 'import json; print json.load(open("'$CFG'"))["SPECTRUM_BROWSER_HOME"]'
)

# Avoid importing anything from the source tree as this has to live by itself on the mobgodb machine.
PYTHONPATH=$PYTHONPATH:${SB_HOME}/services/dbmonitor

cmd="nohup ${PYTHON} ${SB_HOME}/services/dbmonitor/ResourceMonitor.py --dbpath ${DBPATH} --pidfile ${PIDFILE} >>${LOGFILE} 2>&1 &"
sudo -u ${RUN_AS} -g ${RUN_AS_GROUP} bash -c "export PYTHONPATH=${PYTHONPATH}; $cmd"
