#!/bin/sh

CFG=/etc/msod/MSODConfig.json
PIDFILE=/tmp/spectrumdb.pid
LOGFILE=/var/log/spectrumdb
PYTHON=/usr/local/bin/python2.7
PYTHONPATH=/usr/local/lib/python2.7/site-packages/

OPTIND=1
while getopts "p:l:u:g:" opt; do
    case "$opt" in
        p)  PIDFILE=$OPTARG
            ;;
        l)  LOGFILE=$OPTARG
            ;;
        u)  RUN_AS=$OPTARG
            ;;
        g)  RUN_AS_GROUP=$OPTARG
            ;;
    esac
done
shift "$((OPTIND-1))"

if [ ! -f "$CFG" ]; then
    exit -1
fi

SB_HOME=$(
    ${PYTHON} -c 'import json; print json.load(open("'$CFG'"))["SPECTRUM_BROWSER_HOME"]'
)

PYTHONPATH=$PYTHONPATH:${SB_HOME}/services/common:${SB_HOME}/services/spectrumdb

cmd="nohup ${PYTHON} ${SB_HOME}/services/spectrumdb/SpectrumDbService.py --pidfile ${PIDFILE} >>${LOGFILE} 2>&1 &"
bash -c "export PYTHONPATH=${PYTHONPATH};$cmd"
