# Keys for various things in memory cache.
# Put keys here and check for clashes.

PEER_SYSTEM_AND_LOCATION_INFO = "peerSystemAndLocationInfo"
PEER_CONNECTION_MAINTAINER_SEM = "peerConnectionMaintainerSem"
PEER_URL_MAP = "peerUrlMap"
RESOURCEKEYS_CPU = "CPU"
RESOURCEKEYS_VIRTMEM = "VirtMem"
RESOURCEKEYS_DISK = "Disk"
RESOURCEKEYS_NET_SENT = "NetSent"
RESOURCEKEYS_NET_RECV = "NetRecv"
RESOURCEKEYS=[RESOURCEKEYS_CPU, RESOURCEKEYS_VIRTMEM, RESOURCEKEYS_NET_SENT,RESOURCEKEYS_NET_RECV]
